services:
  mongodb:
    image: mongo:7-jammy
    container_name: secure_backend_mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: secure_backend
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
